name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pip=20.3.3
  - pytest
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - pandas==2.2.1
      - scipy
